name: Pandoc HTML Creation

on:
  push:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    defaults:
        run:
            working-directory: ./
    permissions:
        contents: write
    steps:
        - name: clone repo to runner
          uses: actions/checkout@v5
        - name: convert md to html
          uses: docker://pandoc/latex:3.8
          with:
            args: >-
                --standalone
                --output=SPARCNetBootGuide.html
                SPARCNetBootGuide.md
        - name: commit back to repo
          uses: stefanzweifel/git-auto-commit-action@v7